### ISSUE TITLE
Issue with entity number.wattpilot_charging_power

### ISSUE THREAD

**Issue by ccspack** [mk-maddin/wattpilot-HA#16]
This is probably only minor (hopefully easily fixed), but this entity only allows for Max: 16, can this be changed for those of us with the 22kW model, to 32 (Amps) instead? Thank you.

**Comment by mk-maddin** [comment]
can you please verify https://github.com/mk-maddin/wattpilot-HA/releases/tag/v0.1.6 ?
I unfortunately do not have a 22KW model here so implementation is based purely on documentation.

**Comment by ccspack** [comment]
Thanks, I have installed the new update, restarted Home Assistant but still mine still says Max 16. So I disabled and reenable that entity and it still came back with 16 again. I’m in Australia with the 22kW Go V2 just released to our market.

**Comment by ccspack** [comment]
In Solar.Web it shows as “Wattpilot Go 22 J 2.0 AUS

**Comment by tpreugsc** [comment]
the new version lacks 3 sensors, is it on purpose?
![Bildschirm­foto 2022-11-30 um 08 13 49](https://user-images.githubusercontent.com/45978211/204731352-c00cb4fc-d0e9-4e41-844b-5d571412f685.png)

the third one was something with cable unlock...

**Comment by mk-maddin** [comment]
> Thanks, I have installed the new update, restarted Home Assistant but still mine still says Max 16. So I disabled and reenable that entity and it still came back with 16 again. I’m in Australia with the 22kW Go V2 just released to our market.

Maybe the Go V2 has another model id than the 22KW (V1 not GO).
Can you please enable debug logging for:
`logger:
  logs:
    custom_components.wattpilot.number: debug`
    
    
And post the output of log line lookinig like:
<YourWattPilot> - var: _init_platform_specific: <entity_id>: model variant is: <ModelID>

**Comment by mk-maddin** [comment]
> the new version lacks 3 sensors, is it on purpose? ![Bildschirm­foto 2022-11-30 um 08 13 49](https://user-images.githubusercontent.com/45978211/204731352-c00cb4fc-d0e9-4e41-844b-5d571412f685.png)
> 
> the third one was something with cable unlock...

No on purpose - might be related to the wrong model identification

**Comment by ccspack** [comment]
OK it logged this, after following your instructions & a reboot:

`Wattpilot - amp: _init_platform_specific: Wattpilot Charging Power: model variant is: 11`

**Comment by mk-maddin** [comment]
> OK it logged this, after following your instructions & a reboot:
> 
> `Wattpilot - amp: _init_platform_specific: Wattpilot Charging Power: model variant is: 11`

ok... based on documentation a value of 11 indicates a 11KWh device.
Sorry for that bad question, but are you sure you are using 22KWh model?

https://github.com/goecharger/go-eCharger-API-v2/blob/main/apikeys-en.md
![2022-12-01 08_46_25-go-eCharger-API-v2_apikeys-en md at main · goecharger_go-eCharger-API-v2 and 2 m](https://user-images.githubusercontent.com/46523240/204995433-e5165fb5-25df-428d-bdbd-19646ff9b4ca.png)

**Comment by ccspack** [comment]
No problem, I thought that was going to be your next question, but yes I definitely have the 22kW model, that the only speed they sell here & I've seen it charging at 32 Amps.
![IMG_1624](https://user-images.githubusercontent.com/85019945/205010332-4e3e220a-0cdb-43aa-b460-3461cd93e4f1.jpg)

**Comment by mk-maddin** [comment]
ok - so let's try another strategy 

I implemented ( just for you :) ) the diagnostics platform into this component and updated the v0.1.6 pre-release.
https://github.com/mk-maddin/wattpilot-HA/releases/tag/v0.1.6
![2022-12-01 13_33_40-Settings – Home Assistant and 5 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/46523240/205054090-94d43349-d4d0-4b1b-a71a-8e0f42bb832e.png)

So could you please update to this temporary version and sent the diagnostics information?
I will then compare the results and try to find a (correct) variant / model identification.

IMPORTANT NOTE:
I have tried to mask/redact all critical information within the diagnostics output.
Nevertheless I might have overseen a value - as said it was a quick shot - please check the output from your side and feel free to mask/redact additional values that you see as critical. 
Surely, I will be happy if you tell me these value names so I can mask/redact it automatically in future :)

**Comment by ccspack** [comment]
Thanks again, Fee free to delete this from here once you have it. I didn't see anything extra, but its a lot to go through.

[config_entry-wattpilot-034e39711b970bea8ee46d617d1f55ec.json.txt](https://github.com/mk-maddin/wattpilot-HA/files/10132712/config_entry-wattpilot-034e39711b970bea8ee46d617d1f55ec.json.txt)

**Comment by mk-maddin** [comment]
@ccspack : sorry - can you please repost
I just downloaded on my phone where delete was faster than downloaded :(

**Comment by mk-maddin** [comment]
Perfect - thanks deleted the upload as requested :)

**Comment by ccspack** [comment]
Thanks

**Comment by mk-maddin** [comment]
based on the file the "var" value matches 22 ...so exactly as needed
really need to dig into why based on the debug logging the value is 11

**Comment by mk-maddin** [comment]
blame is in me... think I finally found my error
Obvious thing I overlooked multiple times 

The good thing is that diagnostics are now implemented with this :P 

So can you please re-check the re-created 0.1.6 pre-release and inform? - sorry again for all that trouble

**Comment by ccspack** [comment]
Thanks for your time, reinstalled, restarted & working perfectly for me now. Perfect.

**Comment by mk-maddin** [comment]
> Thanks for your time, reinstalled, restarted & working perfectly for me now. Perfect.

Nice to hear :)
Thanks for raising this issue and your cooperation - think this improved the component as a whole and I learned additional topic of diagnostics on this 👍


V0.1.6 now latest - active release
