### ISSUE TITLE
"Wattpilot InternalError" not available for automation

### ISSUE THREAD

**Issue by schwachstelle** [mk-maddin/wattpilot-HA#19]
I would like to notify my cell phone if my Wattpilot runs on an InternalError (which it sometimes does). I can display this entity in a dashboard, but it is not available for automation. It would be great if you could fix this.

**Comment by mk-maddin** [comment]
Can you please provide some more details?
Which entity are you referencing to (entity_id)?
How do you try to use the entity within the automation?
Which version of the wattpilot integration are you using?
Which Home assistant version are you using?
Which firmware version does your wattpilot run at? (maybe attach the diagnostics)

**Comment by schwachstelle** [comment]
Thanks for the quick reply.  :-)

The entity I would like to use is called "Wattpilot InternalError" (sensor.wattpilot_internalerror). I can view it in a dashboard, but when I'm  trying to build an automation (using the graphical editor) which uses this entity as a trigger, there is a long list of Wattpilot entities in the trigger list, but no "Wattpilot InternalError".

I tried to build the automation in yaml:

    alias: Wallbox error
    description: ""
    trigger:
      - platform: device
        device_id: <removed>
        domain: select
        entity_id: sensor.wattpilot_internalerror
        type: current_option_changed
        to: FiAc
    condition: []
    action:
      - service: notify.mobile_app_<removed>
        data:
          message: Wallbox error
    mode: single

But I don't know if this works, I'll have to wait for the next error...

I'm using the latest version of your repo (cloned yesterday) and Home Assistant 2023.4.4 (Frontend 20230411.1 - latest).
My Wattpilot runs on firmware 39.6.

**Comment by mk-maddin** [comment]
This is no issue with the integration.

You are using the "device" trigger platform.
Please use the "state" trigger platform.

![2023-04-17 13_43_05-Settings – Home Assistant and 3 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/46523240/232474494-a3f6ff0c-3358-4a83-9d16-39d69fb89dcc.png)

![image](https://user-images.githubusercontent.com/46523240/232474560-cc17ce27-048b-4f51-a32a-e76e8d3d35ed.png)
