### ISSUE TITLE
Async error

### ISSUE THREAD

**Issue by tschamm** [mk-maddin/wattpilot-HA#2]
When testing the integration, I have the following error in my log.
```
config/custom_components/wattpilot/entities.py:148: RuntimeWarning: coroutine 'async_GetChargerProp' was never awaited
  elif self._source == 'property' and async_GetChargerProp(self._charger, self._identifier) is None:
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by mk-maddin** [comment]
Hi @tschamm 

Which release version are you using?
Could you please enable debug logging and send related log entries?

**Comment by mk-maddin** [comment]
Never mind - I think I found the cause for your error message.
Give me some more minutes to test...

Interesting this did not raise somewhere at my implementations - did you do any change to the .yaml files included in the component to define sensors/switches/butttons etc. ?
If yes it would be great if you can provide which changes you made so I can recreate the issue :)

Thanks

**Comment by mk-maddin** [comment]
@tschamm could you please confirm if this fixes your issue.
I will then create a new release out of it.

Thanks

**Comment by mk-maddin** [comment]
as of #4 I assume this issue is closed ;)
