### ISSUE TITLE
Since HA 2023.5.x async_local_push failed

### ISSUE THREAD

**Issue by thecem** [mk-maddin/wattpilot-HA#20]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.wattpilot.entities
Source: custom_components/wattpilot/entities.py:314
Integration: Fronius Wattpilot (documentation)
First occurred: 13:41:58 (2 occurrences)
Last logged: 13:41:58

Wattpilot_33054860_AK3_K - loc: async_local_push failed: No entity id specified for entity Wattpilot_33054860_AK3_K Local Time (homeassistant.exceptions.NoEntitySpecifiedError)
Wattpilot_33054860_AK3_K - rbt: async_local_push failed: No entity id specified for entity Wattpilot_33054860_AK3_K Reboot Timer (homeassistant.exceptions.NoEntitySpecifiedError)

**Comment by mk-maddin** [comment]
can you please provide diagnostics information?

**Comment by thecem** [comment]
thx for your explanaition!
