### ISSUE TITLE
load balancing - select appears to be incorrect

### ISSUE THREAD

**Issue by kryanth** [mk-maddin/wattpilot-HA#21]
Hi,

I have two fronius WattPilots set up, and use the load balancing mechanism.

HA throws a lot of these errors:

Logger: custom_components.wattpilot.select
Source: custom_components/wattpilot/select.py:115
Integration: Fronius Wattpilot ([documentation](https://github.com/mk-maddin/wattpilot-HA))
First occurred: June 29, 2023 at 8:45:02 PM (27276 occurrences)
Last logged: 2:24:07 PM

LHS Charger - lot: _async_update_validate_platform_state failed: state None not within options_id values: {0: 'Static', 1: 'Dynamic'}
RHS Charger - lot: _async_update_validate_platform_state failed: state None not within options_id values: {0: 'Static', 1: 'Dynamic'}

There is a setting "maximum current" (in amps) that goes up to 32A - the load balancing selector is attempting to use those values when it reads in the data. There doesn't appear to be a field in your configuration to match this, but I think this bit:

id: lot
    name: "Load Balancing"
    options:
      0: "Static"
      1: "Dynamic"
    description: "Load Balancing Type"
    icon: "mdi:scale-balance"
    enabled: False
    entity_category: config

is actually referencing the maximum current (so should be an array [10","16","20","24","32"] I think by default, (you can edit those values so it may just be a integer in the range 1-32. If I use the selector to set dynamic, it will set that value in the App to 1A (which is not much). 

Its plausible to want to configure this in automations, as the load balancing feature is quite useful, but there are definitely times when I want to de-prioritise the charging so I can do other things (also the PV surplus mode is great, but can only be active on one wattpilot at a time).

**Comment by kryanth** [comment]
Using software version V39.6 on the wattpilots (which appears to introduce dynamic load balancing), and app version 1.7.5

**Comment by mk-maddin** [comment]
Please have a look at: https://github.com/mk-maddin/wattpilot-HA/commit/f9f848cbdda850c53632f2724dd48322926c5d67
This corrects the possibility to enable / disable load balancing from HA.
For providing the possibility to adjusting the Amp values I unfortunately do not have a solution as of now.
The AMP values of load balancing are stored as a namespace value with time stamp - not as a normal integer/float/double to be used as a numeric value. I can only read the values at the moment as sensor.

There would be the need to investigate on how to set namespace values using Wattpilot API, but to be truth I do not have the time to investigate into this at the moment.

**Comment by kryanth** [comment]
G'day,
confirmed this works. Will see if I can find a window to play with setting it as well! 
I've since updated the Wattpilots to the latest (40.7) and it works fine with that as well. 
cheers
