### ISSUE TITLE
no entities on 2023.9.1

### ISSUE THREAD

**Issue by chrisrock1984** [mk-maddin/wattpilot-HA#26]
After updating to 2023.9.1, and re-configuring the addon, no entities are found.
I have also tried to restart HA as well as the Wattpilot itself.
It did not solve the problem.

Has anyone the same issues?

**Comment by tpreugsc** [comment]
Sorry, I can‘t confirm! No reconfiguration, I just installed the update.

**Comment by chrisrock1984** [comment]
deleted everything and re-installed it again - works now
