### ISSUE TITLE
No device or entity after update HA 2023.9

### ISSUE THREAD

**Issue by dartymath** [mk-maddin/wattpilot-HA#27]
Dear all,
i have an issue after updating my HA to 2023.9 -> now i have no device or entity on the system and remain the same after removal and reinstallation of the addon.

Home Assistant 2023.9.2
Supervisor 2023.08.3
Operating System 10.5
Interface utilisateur : 20230911.0 - latest

Home Assistant Core
Wattpilot - rbt: async_local_push failed: Attribute hass is None for <entity None=126837216> (builtins.RuntimeError)
09:05:05 – (ERREUR) Fronius Wattpilot (intégration personnalisée) - message survenu pour la première fois à 09:04:45 et apparu 99 fois.
wattpilot: Not adding entity with invalid device info: Invalid device info {'default_manufacturer': 'fronius', 'default_model': 'wattpilot_V2', 'default_name': 'Wattpilot_91022098', 'hw_version': '22 KW', 'identifiers': {('wattpilot', '91022098')}, 'sw_version': '40.7'} for 'wattpilot' config entry: device info needs to either describe a device, link to existing device or provide extra information.
09:05:00 – (ERREUR) Capteur - message survenu pour la première fois à 09:05:00 et apparu 22 fois.
wattpilot: Not adding entity with invalid device info: Invalid device info {'default_manufacturer': 'fronius', 'default_model': 'wattpilot_V2', 'default_name': 'Wattpilot_91022098', 'hw_version': '22 KW', 'identifiers': {('wattpilot', '91022098')}, 'sw_version': '40.7'} for 'wattpilot' config entry: device info needs to either describe a device, link to existing device or provide extra information.
09:05:00 – (ERREUR) Commutateur - message survenu pour la première fois à 09:05:00 et apparu 10 fois.
wattpilot: Not adding entity with invalid device info: Invalid device info {'default_manufacturer': 'fronius', 'default_model': 'wattpilot_V2', 'default_name': 'Wattpilot_91022098', 'hw_version': '22 KW', 'identifiers': {('wattpilot', '91022098')}, 'sw_version': '40.7'} for 'wattpilot' config entry: device info needs to either describe a device, link to existing device or provide extra information.
09:05:00 – (ERREUR) Sélectionner - message survenu pour la première fois à 09:05:00 et apparu 8 fois.
wattpilot: Not adding entity with invalid device info: Invalid device info {'default_manufacturer': 'fronius', 'default_model': 'wattpilot_V2', 'default_name': 'Wattpilot_91022098', 'hw_version': '22 KW', 'identifiers': {('wattpilot', '91022098')}, 'sw_version': '40.7'} for 'wattpilot' config entry: device info needs to either describe a device, link to existing device or provide extra information.
09:05:00 – (ERREUR) Nombre - message survenu pour la première fois à 09:05:00 et apparu 7 fois.
wattpilot: Not adding entity with invalid device info: Invalid device info {'default_manufacturer': 'fronius', 'default_model': 'wattpilot_V2', 'default_name': 'Wattpilot_91022098', 'hw_version': '22 KW', 'identifiers': {('wattpilot', '91022098')}, 'sw_version': '40.7'} for 'wattpilot' config entry: device info needs to either describe a device, link to existing device or provide extra information.
09:05:00 – (ERREUR) Bouton - message survenu pour la première fois à 09:05:00 et apparu 4 fois.
wattpilot - async_registerServic: service already exists: set_goe_cloud
09:04:59 – (AVERTISSEMENT) Fronius Wattpilot (intégration personnalisée) - message survenu pour la première fois à 09:04:59 et apparu 3 fois.
a2203273a155cd06a112fdc94ed575ed - PropertyUpdateHandler: Could not 'self' execute async: 'a2203273a155cd06a112fdc94ed575ed' (builtins.KeyError)
09:04:59 – (ERREUR) Fronius Wattpilot (intégration personnalisée) - message survenu pour la première fois à 09:04:57 et apparu 62 fois.

Could you help me please

[config_entry-wattpilot-a2203273a155cd06a112fdc94ed575ed.json.txt](https://github.com/mk-maddin/wattpilot-HA/files/12594475/config_entry-wattpilot-a2203273a155cd06a112fdc94ed575ed.json.txt)

**Comment by mk-maddin** [comment]
You are still using 0.1.7 version of the integration.
Please update to latest.

**Comment by mk-maddin** [comment]
The issue you described was already fixed here and is included in 0.1.8 - see https://github.com/mk-maddin/wattpilot-HA/commit/766e4e001f1fd97b0f77c0dda0134c152eccba72
