### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by Biyadh00** [mk-maddin/wattpilot-HA#28]
Does not work with 2023.9.2 software.

**Comment by jurajOn** [comment]
Yes. Me too. There was also a firmware update 40.7.

**Comment by tpreugsc** [comment]
Can't confirm. 40.7 firmware and 2023.9.2, all running fine. How can I confirm the version of this integration in my homeassistant system? It's possible, that I don't have the latest version installed.

**Comment by mk-maddin** [comment]
Well... "it's not working" is not very helpful to get your issue resolved.
Help me to help you.

Provide log files, error messages, diagnostics output etc.
Thanks

**Comment by Biyadh00** [comment]
reinstall and get some error
Logger: custom_components.wattpilot.utils
Source: custom_components/wattpilot/utils.py:96
Integration: Fronius Wattpilot ([documentation](https://github.com/mk-maddin/wattpilot-HA))
First occurred: 11:45:22 (965 occurrences)
Last logged: 11:46:39

114aad62f3ffa75eb433c2f66e3dd86e - PropertyUpdateHandler: Could not 'self' execute async: '114aad62f3ffa75eb433c2f66e3dd86e' (builtins.KeyError)
ead598af3b274b70e0c98a731495896e - PropertyUpdateHandler: Could not 'self' execute async: 'ead598af3b274b70e0c98a731495896e' (builtins.KeyError)

**Comment by Biyadh00** [comment]
> Can't confirm. 40.7 firmware and 2023.9.2, all running fine. How can I confirm the version of this integration in my homeassistant system? It's possible, that I don't have the latest version installed.

WP 40.7, HA 2023.09.2 OS 10.5

**Comment by mk-maddin** [comment]
Please attache diagnostics - see screenshot below.
I have three wattpilot (2xV2, 1xV1; fw versions 40.7; 39.6 38.5) in 2 HA instance (2023.9.2 & 2023.9.1) parallel active and cannot confirm a general error from my tests.
Have you completely deleted the device; restarted home assistant; recreated the device?
![image](https://github.com/mk-maddin/wattpilot-HA/assets/46523240/ee89231d-7ab3-4bf5-ac3f-47f294599951)

**Comment by Biyadh00** [comment]
> Please attache diagnostics - see screenshot below.

Completely deleted, restarted, reinstalled. The situation same. I don't have an entity either.
![Screenshot 2023-09-15 at 12 44 17](https://github.com/mk-maddin/wattpilot-HA/assets/137677970/95d41ebb-7f41-4cff-b987-9c7da178e5ff)

**Comment by Biyadh00** [comment]
> Please attache diagnostics - see screenshot below.
> I have three wattpilot (2xV2, 1xV1; fw versions 40.7; 39.6 38.5) in 2 HA instance (2023.9.2 & 2023.9.1) parallel active and cannot confirm a general error from my tests.
> Have you completely deleted the device; restarted home assistant; recreated the device?
> To me this looks like the HA device entry of your wattpilot got corrupted during your upgrade to 2023.9.2.
> ![image](https://user-images.githubusercontent.com/46523240/268254924-ee89231d-7ab3-4bf5-ac3f-47f294599951.png)

The solution: Download the zip from github, manually replace /custom_components/wattpilot and now working :) Thnx for all.

**Comment by mk-maddin** [comment]
yes..if you did not have hte "diagnostics" button at all your version was like pre V0.1.6 ;)
