### ISSUE TITLE
not working after Wattpilot Firmware Update to 40.7

### ISSUE THREAD

**Issue by alex156** [mk-maddin/wattpilot-HA#29]
Hi, the Integration is not working after Firmware update 40.7 on Wattpilot.

I get lots of errors in the Ptorokoll

tryed and downloaded the latest version just today

**Comment by alex156** [comment]
thats right "it´s not working" is not helpful, i´m sorry. thought you might test it yourself by updating Wattpilot but ok.

Heres the logfile of Home Assistant, logging the foults when trying to connect to Wattpilot by adding IP an Password.

[home-assistant_wattpilot_2023-09-18T15-03-42.503Z.log](https://github.com/mk-maddin/wattpilot-HA/files/12664267/home-assistant_wattpilot_2023-09-18T15-03-42.503Z.log)

**Comment by mk-maddin** [comment]
As described wihtin https://github.com/mk-maddin/wattpilot-HA/issues/28#issuecomment-1721053196 myself and others have devices running with 40.7 absolutely fine.

Thanks for the log this helps on my first guess, but for a more certain analyses as the one below the integration diagnostics information is needed. 

As of your log you have exactly the same situation as in the issue already linked above: 
https://github.com/mk-maddin/wattpilot-HA/issues/28
-> You are using not the latest version - the "Invalid device info" error you are seeing was fixed here: https://github.com/mk-maddin/wattpilot-HA/commit/766e4e001f1fd97b0f77c0dda0134c152eccba72
Based on this please do the following:
1. Remove wattpilot device from your home assistant
2. Update the wattpilot integration on file level / via HACS
3. Restart home assistant (do not only reload the configuration as this does not take the updated integration active)
4. Re-add your wattpilot device into home assistant

Thank you for your feedback about this procedure solving / not resolving your issue.

**Comment by alex156** [comment]
_(do not only reload the configuration as this does not take the updated integration active)_

was the issue...

Thanks!
