### ISSUE TITLE
Make HACS installable

### ISSUE THREAD

**Issue by codeclinic** [mk-maddin/wattpilot-HA#33]
Hi, could you possibly make this, so it could be installed via HACS?

Thanks.

**Comment by mk-maddin** [comment]
Can you explain your issue in detail?
What did you try? Where did it fail? 

The integration can be installed via HACS as far as I know (even I do not use personally).
Here is a screenshot of my test instance showing the integration from HACS...
![Screenshot 2023-12-11 105547](https://github.com/mk-maddin/wattpilot-HA/assets/46523240/2718db31-9786-44b5-ae4e-94575677c793)

**Comment by mk-maddin** [comment]
I have added the HACS installation description into readme

https://github.com/mk-maddin/wattpilot-HA#install-with-hacs

**Comment by youbet1980** [comment]
It does not appear in hacs when searching for it. here are 2 screenshots. I also tried on another home assistant and same thing.

![Screen Shot 2024-02-09 at 1 33 48 pm](https://github.com/mk-maddin/wattpilot-HA/assets/48540186/0d91e273-1cdd-4588-aa33-d60f5a13e3ea)
![Screen Shot 2024-02-09 at 1 33 52 pm](https://github.com/mk-maddin/wattpilot-HA/assets/48540186/a661f54c-f590-47df-acb8-c36046930fb9)

**Comment by mk-maddin** [comment]
https://github.com/mk-maddin/wattpilot-HA?tab=readme-ov-file#install-with-hacs

**Comment by youbet1980** [comment]
Thank you. It worked for me by following your instructions.
