### ISSUE TITLE
Error validating platform state 10048

### ISSUE THREAD

**Issue by WillooWisp** [mk-maddin/wattpilot-HA#36]
**Describe the issue you are experiencing**
A lot of the same error in log regarding update validate platform state 10048 not matching any option for:

wattpilot_V2
by fronius
Firmware: 40.7
Hardware: 22 KW

**Describe the expected behavior**
No errors in log.

**To Reproduce**
Update to latest HA.

**What version of Home Assistant Core is installed**
2024.1.2

**What version of Wattpilot integration is installed**
Latest release 0.1.9

**What version of Wattpilot are you using**
22KW-V2

**Error message shown within Home Assistant log**
2024-01-07 18:15:23.607 ERROR (MainThread) [custom_components.wattpilot.select] Wattpilot - awc: _async_update_validate_platform_state failed: state 10048 not within options_id values: {0: 'Austria', 10043: 'Belgium', 10016: 'Bulgaria', 10003: 'Croatia', 10019: 'Czechia', 10024: 'Denmark DK1', 10036: 'Denmark DK2', 10020: 'Estonia', 10004: 'Finland', 10015: 'France', 1: 'Germany', 10006: 'Greece', 10042: 'Hungary', 10017: 'Italy Calabria', 10031: 'Italy Centre-Noth', 10009: 'Italy Centre-South', 10034: 'Italy North', 10023: 'Italy SacoAC', 10001: 'Italy SacoDC', 10029: 'Italy Sardinia', 10005: 'Italy Sicily', 10041: 'Italy South', 10010: 'Latvia', 10030: 'Lithuania', 10012: 'Montenegro', 10038: 'Netherlands', 10057: 'Norway Elspot1', 10058: 'Norway Elspot2', 10059: 'Norway Elspot3', 10060: 'Norway Elspot4', 10061: 'Norway Elspot5', 10021: 'Norway NO2NSL', 10037: 'Poland', 10027: 'Portugal', 10044: 'Romania', 10039: 'Serbia', 10040: 'Slovakia', 10025: 'Slovenia', 10018: 'Spain', 10062: 'Sweden Elspot1', 10063: 'Sweden Elspot2', 10064: 'Sweden Elspot3', 10065: 'Sweden Elspot4', 10035: 'Switzerland', 10002: 'Ukraine'}

**Diagnostics information of Wattpilot integration**
{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2024.1.2",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Stockholm",
    "os_name": "Linux",
    "os_version": "4.4.302+",
    "run_as_root": true
  },
  "custom_components": {
    "ltss": {
      "version": "2.1.0",
      "requirements": [
        "sqlalchemy>=2.0,<3.0",
        "psycopg2-binary>=2.8,<3.0",
        "geoalchemy2>=0.13,<1.0"
      ]
    },
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "wattpilot": {
      "version": "0.1.9",
      "requirements": [
        "wattpilot>=0.1",
        "pyyaml>=5.3.0",
        "importlib_metadata>=4.0.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "wattpilot",
    "name": "Fronius Wattpilot",
    "version": "0.1.9",
    "config_flow": true,
    "documentation": "https://github.com/mk-maddin/wattpilot-HA",
    "requirements": [
      "wattpilot>=0.1",
      "pyyaml>=5.3.0",
      "importlib_metadata>=4.0.0"
    ],
    "dependencies": [
      "sensor",
      "switch",
      "select",
      "number",
      "button",
      "diagnostics"
    ],
    "codeowners": [
      "@mk-maddin"
    ],
    "iot_class": "local_polling",
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "afa41b80d905c80ea3296d7d22b72156",
      "version": 1,
      "minor_version": 1,
      "domain": "wattpilot",
      "title": "Wattpilot",
      "data": {
        "friendly_name": "Wattpilot",
        "ip_address": "**REDACTED**",
        "password": "**REDACTED**",
        "timeout": 15
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    },
    "charger_properties": {
      "stao": null,
      "alw": false,
      "acu": null,
      "acui": null,
      "adi": false,
      "acl": null,
      "dwo": null,
      "tpa": 10131.18359,
      "sse": "91023946",
      "eto": 2845782,
      "etop": 2845782,
      "wifis": "**REDACTED**",
      "scas": 2,
      "scan": "**REDACTED**",
      "lwf": 933708461,
      "scaa": 933715664,
      "wst": 3,
      "wsc": 0,
      "wsm": "933708459931 WIFI_STA_DISCONNECTED ssid=\"Fjorden-IoT-Outdoor\" bssid=7E:A7:41:6E:00:5C reason=34(MISSING_ACKS)",
      "wsl": [
        [
          933708459931,
          "Fjorden-IoT-Outdoor",
          "7E:A7:41:6E:00:5C",
          "MISSING_ACKS"
        ]
      ],
      "wsms": 3,
      "ccw": {
        "__type": "<class 'types.SimpleNamespace'>",
        "repr": "namespace(ssid='Fjorden-IoT-Outdoor', encryptionType=3, pairwiseCipher=4, groupCipher=4, b=True, g=True, n=True, lr=False, wps=False, ftmResponder=False, ftmInitiator=False, channel=1, bssid='7E:A7:41:6E:00:5C', ip='192.168.20.3', netmask='255.255.255.0', gw='192.168.20.1', ipv6=['FE80::E8B:95FF:FE70:B360'])"
      },
      "wfb": null,
      "wcb": "7E:A7:41:6E:00:5C",
      "wpb": [
        "7E:A7:41:6D:FC:26"
      ],
      "nif": "st",
      "dns": {
        "__type": "<class 'types.SimpleNamespace'>",
        "repr": "namespace(dns0='192.168.20.1', dns1='0.0.0.0', dns2='0.0.0.0')"
      },
      "hsts": "Wattpilot_91023946",
      "hsta": "Wattpilot_91023946",
      "host": "Wattpilot_91023946",
      "rssi": -70,
      "lssfc": 933708461,
      "lsstc": 933717713,
      "ehs": 287500,
      "efh": 105968,
      "efh32": 105968,
      "efh8": 68880,
      "fem": 1,
      "sbe": true,
      "emfh": 80896,
      "emhb": 47092,
      "eci": {
        "__type": "<class 'types.SimpleNamespace'>",
        "repr": "namespace(model=1, features=50, cores=2, revision=300)"
      },
      "ecf": {
        "__type": "<class 'types.SimpleNamespace'>",
        "repr": "namespace(source=1, source_freq_mhz=320, div=2, freq_mhz=160)"
      },
      "efi": {
        "__type": "<class 'types.SimpleNamespace'>",
        "repr": "namespace(segment_count=3, spi_mode=2, spi_speed=0, spi_size=3)"
      },
      "abm": "0C:8B:95:70:B3:60",
      "dbm": "0C:8B:95:70:B3:60",
      "cbm": null,
      "obm": null,
      "macs": "0C:8B:95:70:B3:60",
      "maca": "0C:8B:95:70:B3:61",
      "esr": [
        12,
        12
      ],
      "rr": 3,
      "wae": true,
      "fwan": "Wattpilot_91023946",
      "wan": "Wattpilot_91023946",
      "facwak": true,
      "wak": false,
      "wda": false,
      "wen": true,
      "wsmr": -90,
      "wapc": 1,
      "waap": 4,
      "swc": false,
      "pass": true,
      "tse": false,
      "ts": "europe.pool.ntp.org",
      "tssm": 0,
      "tssi": 3600000,
      "tsss": 0,
      "tof": 60,
      "tds": 1,
      "tzt": "",
      "utc": "2024-01-07T17:22:00.632",
      "loc": "2024-01-07T18:22:00.633 +01:00",
      "led": {
        "__type": "<class 'types.SimpleNamespace'>",
        "repr": "namespace(id=16, name='Pulsate', norwayOverlay=True, modeOverlay=True, subtype='renderCmds', ranges=[namespace(from=0, to=15, fade='2048ms', colors0=['#0000FF'], colors1=['#000000']), namespace(from=16, to=31, colors=['#000000'])])"
      },
      "ledo": null,
      "lbr": 75,
      "lmo": 3,
      "ama": 32,
      "tcl": null,
      "die": true,
      "dii": false,
      "la1": 16,
      "la3": 16,
      "di1": false,
      "pgr": false,
      "pdi": false,
      "clp": [
        10,
        16,
        20,
        24,
        32
      ],
      "al1": 10,
      "al2": 16,
      "al3": 20,
      "al4": 24,
      "al5": 32,
      "bam": 3,
      "bac": 3,
      "lbp": null,
      "lbh": null,
      "amp": 16,
      "ffna": "Wattpilot_91023946",
      "fna": "Wattpilot_91023946",
      "isgo": true,
      "simo": true,
      "aus": false,
      "cy": "sweden",
      "mukw": null,
      "rdbs": 0,
      "rdes": 0,
      "rdbf": 0,
      "rdef": 0,
      "rdre": 0,
      "rdpl": 0,
      "rdbse": null,
      "rdese": null,
      "rdbfe": null,
      "rdefe": null,
      "rdree": null,
      "rdple": null,
      "cid": "#0000FF",
      "cwc": "#FFFF00",
      "cch": "#00FFFF",
      "cfi": "#00FF00",
      "ust": 2,
      "lck": 2,
      "sch_week": {
        "__type": "<class 'types.SimpleNamespace'>",
        "repr": "namespace(control=3, ranges=[namespace(begin=namespace(hour=0, minute=0, second=0), end=namespace(hour=0, minute=0, second=0)), namespace(begin=namespace(hour=0, minute=0, second=0), end=namespace(hour=0, minute=0, second=0))])"
      },
      "sch_satur": {
        "__type": "<class 'types.SimpleNamespace'>",
        "repr": "namespace(control=3, ranges=[namespace(begin=namespace(hour=0, minute=0, second=0), end=namespace(hour=0, minute=0, second=0)), namespace(begin=namespace(hour=0, minute=0, second=0), end=namespace(hour=0, minute=0, second=0))])"
      },
      "sch_sund": {
        "__type": "<class 'types.SimpleNamespace'>",
        "repr": "namespace(control=3, ranges=[namespace(begin=namespace(hour=3, minute=0, second=0), end=namespace(hour=5, minute=0, second=0)), namespace(begin=namespace(hour=0, minute=0, second=0), end=namespace(hour=0, minute=0, second=0))])"
      },
      "nmo": false,
      "dco": true,
      "fsp": false,
      "frci": true,
      "rsd": 2,
      "rfd": 3203346,
      "rss": 0,
      "rfs": 0,
      "ris": 0,
      "rssa": 0,
      "rco": 0,
      "ria": 0,
      "rfa": 8,
      "rsu": 0,
      "rfu": 2,
      "acs": 0,
      "frc": 0,
      "rbc": 11,
      "rbt": 1297889634,
      "car": 1,
      "err": 0,
      "cbl": 32,
      "pha": [
        false,
        false,
        false,
        true,
        true,
        true
      ],
      "wh": 21702.94231,
      "trx": null,
      "fwv": "40.7",
      "arv": "1.2.1",
      "ccu": null,
      "oem": "fronius",
      "typ": "wattpilot_V2",
      "fwc": "0.0.1-50",
      "ccrv": "0.0.1-50",
      "apd": {
        "__type": "<class 'types.SimpleNamespace'>",
        "repr": "namespace(project_name='wattpilot_hw5+', version='40.7', secure_version=0, timestamp='Aug 10 2023 15:28:10', idf_ver='v5.2-dev-363-ga818426cb2', sha256='0b9e08e51c24a111')"
      },
      "otap": {
        "__type": "<class 'types.SimpleNamespace'>",
        "repr": "namespace(type=0, subtype=17, address=4849664, size=3145728, label='app_1', encrypted=True)"
      },
      "part": [
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(type=1, subtype=2, address=65536, size=262144, label='nvs', encrypted=False)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(type=1, subtype=2, address=327680, size=262144, label='nvsFac', encrypted=False)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(type=1, subtype=1, address=589824, size=4096, label='phy_init', encrypted=False)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(type=1, subtype=0, address=593920, size=8192, label='otadata', encrypted=True)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(type=0, subtype=16, address=1703936, size=3145728, label='app_0', encrypted=True)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(type=0, subtype=17, address=4849664, size=3145728, label='app_1', encrypted=True)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(type=1, subtype=4, address=7995392, size=4096, label='nvs_key', encrypted=True)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(type=1, subtype=3, address=7999488, size=65536, label='coredump', encrypted=True)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(type=64, subtype=1, address=8065024, size=65536, label='keys', encrypted=True)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(type=1, subtype=130, address=8130560, size=258048, label='spiffs', encrypted=False)"
        }
      ],
      "pto": 61440,
      "lse": true,
      "mws": true,
      "cdi": {
        "__type": "<class 'types.SimpleNamespace'>",
        "repr": "namespace(type=1, value=7257938)"
      },
      "lch": 1221070216,
      "lccfi": 1221070216,
      "lccfc": 1249831810,
      "lcctc": 1242573872,
      "tma": [
        5,
        -0.5
      ],
      "amt": 32,
      "nrg": [
        225.6799927,
        225.9900055,
        228.4700012,
        1.549999952,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "modelStatus": 5,
      "msi": 5,
      "lmsc": 1249829373,
      "mca": 6,
      "awc": 10048,
      "awp": 2.150000095,
      "awcp": {
        "__type": "<class 'types.SimpleNamespace'>",
        "repr": "namespace(start=1704646800, end=1704650400, marketprice=10.60999966)"
      },
      "awpl": [
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704646800, end=1704650400, marketprice=10.60999966)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704650400, end=1704654000, marketprice=10.35999966)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704654000, end=1704657600, marketprice=10.05000019)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704657600, end=1704661200, marketprice=9.329999924)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704661200, end=1704664800, marketprice=9.119999886)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704664800, end=1704668400, marketprice=8.390000343)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704668400, end=1704672000, marketprice=8.699999809)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704672000, end=1704675600, marketprice=8.430000305)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704675600, end=1704679200, marketprice=8.180000305)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704679200, end=1704682800, marketprice=7.909999847)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704682800, end=1704686400, marketprice=7.849999905)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704686400, end=1704690000, marketprice=8.210000038)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704690000, end=1704693600, marketprice=9.430000305)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704693600, end=1704697200, marketprice=11.11999989)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704697200, end=1704700800, marketprice=12.10999966)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704700800, end=1704704400, marketprice=12.06999969)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704704400, end=1704708000, marketprice=11.39000034)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704708000, end=1704711600, marketprice=10.55000019)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704711600, end=1704715200, marketprice=9.779999733)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704715200, end=1704718800, marketprice=9.489999771)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704718800, end=1704722400, marketprice=10.25)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704722400, end=1704726000, marketprice=11.06000042)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704726000, end=1704729600, marketprice=12.80000019)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704729600, end=1704733200, marketprice=13.22999954)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704733200, end=1704736800, marketprice=13)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704736800, end=1704740400, marketprice=12.21000004)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704740400, end=1704744000, marketprice=11.42000008)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704744000, end=1704747600, marketprice=10.27999973)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704747600, end=1704751200, marketprice=10)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(start=1704751200, end=1704754800, marketprice=9.149999619)"
        }
      ],
      "ido": null,
      "frm": 1,
      "fup": true,
      "ful": true,
      "fst": 1400,
      "fmt": 300000,
      "ftt": 36000,
      "fte": 30000,
      "fre": true,
      "fap": true,
      "cco": 20,
      "esk": true,
      "fzf": false,
      "fot": 20,
      "fam": 20,
      "sh": 200,
      "psh": 500,
      "po": -300,
      "zfo": 200,
      "psmd": 10000,
      "sumd": 10000,
      "mpwst": 120000,
      "mptwt": 600000,
      "fi23": false,
      "fio23": false,
      "ferm": 1,
      "fmmp": 0,
      "ftlf": false,
      "ftls": null,
      "fntp": null,
      "lpsc": 1297869544,
      "fbuf_age": 1297885170,
      "fml": "grid",
      "fbuf_pGrid": 1080.599976,
      "fbuf_pPv": 0,
      "fbuf_akkuSOC": null,
      "fbuf_akkuMode": null,
      "fbuf_pAkku": null,
      "fbuf_pAcTotal": null,
      "fbuf_ohmpilotState": null,
      "fbuf_ohmpilotTemperature": null,
      "fit": 1,
      "pvopt_deltaP": -1086.966675,
      "pnp": 1,
      "pvopt_deltaA": -0.573478222,
      "pvopt_averagePGrid": 1086.966675,
      "pvopt_averagePPv": 0,
      "pvopt_averagePAkku": 0,
      "pvopt_averagePOhmpilot": 0,
      "pvopt_specialCase": 0,
      "ct": "",
      "mci": 0,
      "mcpd": 0,
      "mcpea": null,
      "su": false,
      "sua": false,
      "hws": true,
      "hsa": true,
      "var": 22,
      "loe": true,
      "log": "",
      "lop": 50,
      "lof": 12,
      "map": [
        1,
        2,
        3
      ],
      "upo": false,
      "pwm": 1,
      "lfspt": null,
      "fsptws": 630632065,
      "spl3": 4200,
      "psm": 0,
      "ocu": [
        "__default"
      ],
      "ocuca": true,
      "ocs": 0,
      "ocp": 0,
      "ocm": "",
      "ocl": null,
      "oca": null,
      "opad": {
        "__type": "<class 'types.SimpleNamespace'>",
        "repr": "namespace(project_name='wattpilot_hw5+', version='40.5', secure_version=0, timestamp='Jul  4 2023 10:31:14', idf_ver='v5.2-dev-363-ga818426cb2', sha256='f18257f84885a033')"
      },
      "cwe": true,
      "cca": true,
      "cws": true,
      "cwsc": true,
      "cwsca": 964581445,
      "chr": true,
      "clea": 964562610,
      "cle": "esp_transport_write() returned 0, transport_error=ESP_OK, tls_error_code=0, tls_flags=0, errno=0",
      "cpe": true,
      "cpr": true,
      "cus": 3,
      "ffb": 0,
      "ffba": null,
      "fhz": 50,
      "rcd": null,
      "onv": "40.7",
      "lom": null,
      "loa": 6,
      "los": "{\"chg\":[[\"91023946\",true,null,50,12,[1,2,3],false,16]]}",
      "lot": {
        "__type": "<class 'types.SimpleNamespace'>",
        "repr": "namespace(amp=32, dyn=32, sta=32, ts=0)"
      },
      "loty": 1,
      "wcch": 0,
      "wccw": 1,
      "qsc": 0,
      "qsw": 0,
      "cards": [
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(name='n/a', energy=0, cardId=True)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(name='n/a', energy=0, cardId=False)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(name='n/a', energy=0, cardId=False)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(name='n/a', energy=0, cardId=False)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(name='n/a', energy=0, cardId=False)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(name='n/a', energy=0, cardId=False)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(name='n/a', energy=0, cardId=False)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(name='n/a', energy=0, cardId=False)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(name='n/a', energy=0, cardId=False)"
        },
        {
          "__type": "<class 'types.SimpleNamespace'>",
          "repr": "namespace(name='n/a', energy=0, cardId=False)"
        }
      ],
      "ets": 97,
      "lps": 67,
      "tpck": [
        "chargectrl_v4",
        "led",
        "wifi",
        "webserver",
        "mdns",
        "time",
        "cloud",
        "rfid",
        "status",
        "froniusinverter",
        "button",
        "delta_http",
        "delta_cloud",
        "ota_cloud",
        "cmdhandler",
        "loadbalancing",
        "ocpp",
        "remotehttp",
        "remotemdns",
        "remoteping",
        "cloud_send"
      ],
      "tpcm": [
        28,
        5,
        1,
        0,
        0,
        0,
        1,
        0,
        7,
        7,
        0,
        78,
        84,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        6
      ],
      "tsks": [
        [
          "ipc0",
          1,
          5,
          1,
          1,
          0,
          1396
        ],
        [
          "ipc1",
          2,
          5,
          24,
          24,
          0,
          1452
        ],
        [
          "esp_timer",
          3,
          5,
          22,
          22,
          0,
          3244
        ],
        [
          "main",
          4,
          5,
          1,
          1,
          0,
          2508
        ],
        [
          "IDLE",
          5,
          5,
          0,
          0,
          0,
          1680
        ],
        [
          "IDLE",
          6,
          5,
          0,
          0,
          0,
          1684
        ],
        [
          "Tmr Svc",
          7,
          5,
          1,
          1,
          0,
          1400
        ],
        [
          "tiT",
          8,
          5,
          18,
          18,
          0,
          1932
        ],
        [
          "sys_evt",
          9,
          5,
          20,
          20,
          0,
          1840
        ],
        [
          "wifi",
          10,
          5,
          23,
          23,
          0,
          4168
        ],
        [
          "btm_rrm_t",
          11,
          5,
          2,
          2,
          0,
          6036
        ],
        [
          "httpd",
          12,
          5,
          5,
          5,
          0,
          4080
        ],
        [
          "mdns",
          13,
          5,
          1,
          1,
          0,
          1724
        ],
        [
          "cloudSendTask",
          14,
          5,
          5,
          5,
          0,
          2260
        ],
        [
          "nfc_reader_task",
          15,
          5,
          0,
          0,
          0,
          2804
        ],
        [
          "cloud_client",
          16,
          5,
          5,
          5,
          0,
          700
        ],
        [
          "solarDataReques",
          17,
          5,
          10,
          10,
          0,
          1012
        ],
        [
          "smartMeterDataR",
          18,
          5,
          10,
          10,
          0,
          1004
        ],
        [
          "smartMeterListR",
          19,
          5,
          10,
          10,
          0,
          1276
        ]
      ],
      "cci": {
        "__type": "<class 'types.SimpleNamespace'>",
        "repr": "namespace(id='33636968', paired=True, deviceFamily='DataManager', label='Fjorden', model='PILOT', commonName='pilot-0.6e-796400275860610167_1665565746', ip='192.168.20.2', connected=True, reachableMdns=True, reachableUdp=True, reachableHttp=True, status=0, message='ok')"
      },
      "irs": false,
      "facice": true,
      "ice": true,
      "imse": true,
      "iuse": true,
      "immr": 20,
      "ims": "_Fronius-SE-Inverter",
      "imp": "_tcp",
      "isml": false,
      "imd": true,
      "imi": "0",
      "csca": 2,
      "occa": 2,
      "sdca": 2,
      "slca": 2,
      "smca": 2,
      "uaca": 2,
      "rrca": 2,
      "rmdns": false,
      "riul": false,
      "risl": false,
      "rill": false,
      "riml": false,
      "rial": false,
      "smd": {
        "__type": "<class 'types.SimpleNamespace'>",
        "repr": "namespace(ts=1297889201, I1=1.496000051, I2=2.08100009, I3=1.768000007)"
      },
      "cup": 1,
      "data": "**REDACTED**",
      "dll": "**REDACTED**",
      "fck": true,
      "fcc": true,
      "asc": true,
      "fhi": true,
      "cdv": null,
      "mscs": 5,
      "msca": 0,
      "ocppe": false,
      "ocppu": "",
      "ocppg": true,
      "ocppcn": false,
      "ocppss": false,
      "ocpps": false,
      "ocppc": false,
      "ocppca": null,
      "ocppa": false,
      "ocppaa": null,
      "ocppti": null,
      "ocppao": false,
      "ocpplo": true,
      "ocppla": true,
      "ocpph": 3600,
      "ocppi": 0,
      "ocppai": 0,
      "ocppd": "no-card",
      "ocppr": false,
      "ocppcm": 0,
      "ocpplea": null,
      "ocpple": null,
      "ocpprl": false,
      "ocppck": "**REDACTED**",
      "ocppcc": "**REDACTED**",
      "ocppsc": "**REDACTED**",
      "ocppcs": 0,
      "lbs": 934,
      "las": 0,
      "llr": 2,
      "rfide": true,
      "rfe": null,
      "rde": false,
      "lri": null,
      "tsi": null,
      "lrc": null,
      "lrr": null,
      "rtp": 0,
      "rrv": 8,
      "sau": false,
      "loi": false,
      "gme": false,
      "gmk": "",
      "cae": false,
      "cak": "",
      "ens": "",
      "aup": 6,
      "tou": 0,
      "ipw": "",
      "cc4": {
        "__type": "<class 'types.SimpleNamespace'>",
        "repr": "namespace(firmware_installed=True, installed_firmware_valid=True, hwid='v4.6-rts-gd32', firmware_version='0.0.1-50')"
      },
      "cc4st": 2,
      "cc4cs": 0,
      "cc4sp": 0,
      "cc4tl": 32000,
      "cc4ls": 32000,
      "cc4lt": 32000,
      "cc4vm": 11771,
      "cc4vx": 11786,
      "cc4pp": 221,
      "cc4dc": 1000,
      "cc4ss": 17600,
      "cc4ca": false,
      "cc4sf": false,
      "cc4cd": false,
      "cc4i1": false,
      "cc4nl": false,
      "cc4ld": false,
      "cc4lc": false,
      "cc4fu": false,
      "cc4sv": true,
      "cc4tv": true,
      "cc4vr": false,
      "cc42l": true,
      "cc4tt": false,
      "cc4tm": false,
      "cc4rf": false,
      "cc4rv": [
        1550,
        225680,
        225990,
        228470
      ],
      "cc4rc": [
        0,
        0,
        0,
        76
      ],
      "cc4rp": [
        0,
        102,
        8,
        11984
      ],
      "cc4ap": [
        0,
        0,
        0,
        17363
      ],
      "cc4fm": [
        48207,
        50002,
        49995,
        50000
      ],
      "cc4pm": [
        180000,
        329220,
        113334,
        297594
      ],
      "cc4re": [
        0,
        43896969,
        39909638,
        41153779
      ],
      "cc4ae": [
        0,
        44211080,
        40239986,
        41617562
      ],
      "cc4is": 4
    },
    "wattpilot_module": "0.2"
  }
}

**Comment by mk-maddin** [comment]
Can you please share what you selected here within the App?
Seems you found an option which I did not cover there yet :)

Thanks

![IMG_4980](https://github.com/mk-maddin/wattpilot-HA/assets/46523240/7328bf4f-2dbf-4e04-b079-9c7a725dd0df)

**Comment by WillooWisp** [comment]
Ahh, I see.

![Screenshot_20240107_235648_Solarwattpilot.jpg](https://github.com/mk-maddin/wattpilot-HA/assets/3296485/3adf5900-1059-4a69-a3d6-f679755c2833)

**Comment by mk-maddin** [comment]
fixed with commit https://github.com/mk-maddin/wattpilot-HA/commit/5b1d3316f23796bf9dfd88516bee277ddf72dbcd
will be part of next release
