### ISSUE TITLE
Naming of entities misleading

### ISSUE THREAD

**Issue by manutoky** [mk-maddin/wattpilot-HA#40]
Some entity names could be improved / are incorrect:
- number.wattpilot_charging_power: seems to be a setting for the maximum **current** 
- sensor.wattpilot_charging_energy: is actually the charging **power**

My proposal would be to rename sensor.wattpilot_charging_energy to sensor.wattpilot_charging_power and number.wattpilot_charging_power to number.wattpilot_charging_max_current (or similar)

**What version of Home Assistant Core is installed**
2024.04.02

**What version of Wattpilot integration is installed**
Release 0.1.9

**What version of Wattpilot are you using**
 11KW-V2 Firmware 40.7

**Comment by manutoky** [comment]
Just saw after I wrote the issue that there already is [PR39](https://github.com/mk-maddin/wattpilot-HA/pull/39) taking care of this. Feel free to close the issue if you consider merging this PR.

**Comment by mk-maddin** [comment]
fixed in [48d93b6](https://github.com/mk-maddin/wattpilot-HA/commit/48d93b67f27cb50d54ee4f0906a2891260a41e5b)
