### ISSUE TITLE
Update manifest.json to reflect new version 0.2.0 - still says 0.1.9

### ISSUE THREAD

**Issue by pbrooks29** [mk-maddin/wattpilot-HA#42]
manifest.json records the version still as 0.1.9, in the release 0.2.0 files - which will confuse logging diagnosis, and possible confuse the HACS package version update detection.

**Comment by mk-maddin** [comment]
thanks for this information
https://github.com/mk-maddin/wattpilot-HA/commit/3cb755969cdb5f0a28e133bcb0a52e054daec1b1
