### ISSUE TITLE
Wattpilot only charges in 3 phases

### ISSUE THREAD

**Issue by ff-mobil** [mk-maddin/wattpilot-HA#44]
Since installing the integration, my Wattpilot only charges in 3 phases. As soon as the PV system has more than 1.38KW, the Wattpilot switches on and charges with 4KW. What can I do?

**Comment by mk-maddin** [comment]
This setting is independent of the integration.
The integration itself just sets values coming from the wattpillot - the official Wattpilot App always overrides the HA settings.


So what you can do is open the official Wattpilot app -> settings -> Cost Optimisation -> Car Advanced Settings -> "Choose Phase Switch" and select "Only 1 Phase" 
this way your wattpilot never changes to 3 Phase charging - independently of the power your inverter provides.


In general please use the github  I prepared here for issues. 
Thanks
