### ISSUE TITLE
Which Parameter is charging state?

### ISSUE THREAD

**Issue by thecem** [mk-maddin/wattpilot-HA#5]
Which parameter is this: car?

![B58CB7B4-F905-4F74-8620-3B66B32855BE](https://user-images.githubusercontent.com/46648579/164391890-42666980-5baf-466c-b85f-3e4540e37d6f.jpeg)

if yes the mapping is:

1:Idle
2:Charging
3:WaitCar
4:Complete
5:Error

so it must be `Idle` and not `Unknown Error` ?

**Comment by mk-maddin** [comment]
The sensor is the wattpilot attribute "errorstate"

See:  the following entry https://github.com/mk-maddin/wattpilot-HA/blob/dfd2562cc0afda236ad0d35f679d9f7c5d9c6342/custom_components/wattpilot/sensor.yaml#L31
Maybe it should be renamed. Feel free for a commit.

Where are you referencing the mapping from (any link)?

**Comment by thecem** [comment]
Reference: https://github.com/goecharger/go-eCharger-API-v2/blob/main/apikeys-de.md

will have a look this evening….

**Comment by thecem** [comment]
Do you use the adaption of [@joscha82](https://github.com/joscha82/wattpilot/blob/ca98bb3905dacbc11139b09f1d731e175136b429/src/wattpilot/__init__.py#L93) ?
Issue: https://github.com/joscha82/wattpilot/issues/8
thx!

**Comment by ahochsteger** [comment]
@mk-maddin, maybe you're interested in this PR as well, since it provides full Home Assistant support (using MQTT discovery) in a completely generic way (using the property definitions in `wattpilot.yaml`) and supports value mapping for integer enums: https://github.com/joscha82/wattpilot/pull/9

Would be interested if this solves the naming issues.

**Comment by mk-maddin** [comment]
Thanks both.

@thecem: 
in meantime I have implemented an option to define enum values for sensor & select entities independently of the python module (Maybe this helps with language translation in future).

Please check if https://github.com/mk-maddin/wattpilot-HA/commit/c3fc77df44a97a0e44f0a3bf330aef9217e4e6df provides the values needed.

ATTENTION: I have changed the sensor name from "ChargingState" to "CarState" as suggested.

**Comment by mk-maddin** [comment]
Assuming thsi is fine now with update provided as described above :)
