### ISSUE TITLE
chiama async_forward_entry_setup

### ISSUE THREAD

**Issue by danilo-quadrelli** [mk-maddin/wattpilot-HA#53]
Registratore: homeassistant.helpers.frame
Fonte: helpers/frame.py:188
Prima occorrenza: 17:44:39 (1 occorrenze)
Ultima registrazione: 17:44:39

Detected that custom integration 'wattpilot' calls async_forward_entry_setup for integration, wattpilot with title: Wattpilot and entry_id: 01J4ABM4R95WMM1TGA1K680JTV, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/wattpilot/__init__.py, line 98: hass.async_create_task(hass.config_entries.async_forward_entry_setup(entry, platform)), please report it to the author of the 'wattpilot' custom integration

**Comment by mk-maddin** [comment]
this was already fixed in https://github.com/mk-maddin/wattpilot-HA/pull/48
