### ISSUE TITLE
fup: Change PV Surplus

### ISSUE THREAD

**Issue by thecem** [mk-maddin/wattpilot-HA#7]
https://github.com/mk-maddin/wattpilot-HA/blob/0823d823a7af473fcbb4aba0590516920a350058/custom_components/wattpilot/switch.yaml#L19

must be `fup` not `alw` (alw is RO), fup -> PV Surplus -> bool

**Comment by thecem** [comment]
Relevant to switch over the "usePvSurplus" to next Wattpilot on SOC state (separate car integration).

**Comment by mk-maddin** [comment]
Can you please create a PR - as you seem to have it fixed already? 
Thanks :)
