### ISSUE TITLE
websocket - Timeout - charger not connected

### ISSUE THREAD

**Issue by m4tze-smart** [mk-maddin/wattpilot-HA#9]
Hello Community,

I receive some failure and can't connect to the WATTPILOT.
Any else with this problem or hints to solve this problem ?

The WLAN connection with the iOS App is possible.

failure:
d00dbdeb09c030566e41a48acb3b566a - async_setup_entry: Timeout - charger not connected: False (15 sec)
11:50:59 – (FEHLER) Fronius Wattpilot (benutzerdefinierte Integration) - Die Nachricht ist zum ersten Mal um 18. Mai 2022, 09:46:24 aufgetreten und erscheint 4 mal
error from callback <bound method Wattpilot.__on_message of <wattpilot.Wattpilot object at 0x7f9f07c69430>>: __on_message() missing 1 required positional argument: 'message'
11:49:20 – (FEHLER) /usr/local/lib/python3.9/site-packages/websocket/_logging.py - Die Nachricht ist zum ersten Mal um 18. Mai 2022, 09:46:10 aufgetreten und erscheint 9 mal

Logfile:
{"name":"custom_components.wattpilot","message":["d00dbdeb09c030566e41a48acb3b566a - async_setup_entry: Timeout - charger not connected: False (15 sec)","4f6b555084c7f3d0dd6157d573b9d3b3 - async_setup_entry: Timeout - charger not connected: False (150 sec)","49868dd8764b9d1112ca0d365520abc6 - async_setup_entry: Timeout - charger not connected: False (100 sec)","457f504927de9fef4237374a49325222 - async_setup_entry: Timeout - charger not connected: False (100 sec)"],"level":"ERROR","source":["custom_components/wattpilot/__init__.py",63],"timestamp":1652953859.3858526,"exception":"","count":4,"first_occurred":1652859984.6865854},{"name":"websocket","message":["error from callback <bound method Wattpilot.__on_message of <wattpilot.Wattpilot object at 0x7f9f07c69430>>: __on_message() missing 1 required positional argument: 'message'","error from callback <bound method Wattpilot.__on_message of <wattpilot.Wattpilot object at 0x7f9f06a0b7c0>>: __on_message() missing 1 required positional argument: 'message'","error from callback <bound method Wattpilot.__on_message of <wattpilot.Wattpilot object at 0x7f9f04b542e0>>: __on_message() missing 1 required positional argument: 'message'","error from callback <bound method BaseHubConnection.on_socket_error of <signalrcore.hub.auth_hub_connection.AuthHubConnection object at 0x7f9f16c4e220>>: Connection is already closed.","error from callback <bound method Wattpilot.__on_message of <wattpilot.Wattpilot object at 0x7f9efb643a30>>: __on_message() missing 1 required positional argument: 'message'"],"level":"ERROR","source":["/usr/local/lib/python3.9/site-packages/websocket/_logging.py",61],"timestamp":1652953760.0902665,"exception":"","count":9,"first_occurred":1652859970.1090765},

**Comment by tpreugsc** [comment]
Aktuell nicht. Musste allerdings die Wallbox komplett zurücksetzen, damit das addin sauber funktioniert.

mit freundlichen Grüßen 

Till Preugschat

**Comment by m4tze-smart** [comment]
okay, gibt es neben der Reset Card noch einen Hardreset der helfen könnte ?

**Comment by tpreugsc** [comment]
Ist mir nich bekannt. Ich hatte massive Probleme, den Wattpiloten in meinem Mesh zu betreiben(Fritz, mehrere gleiche APs mit der gleichen SSID). Habe jetzt einen separaten Repeater in unmittelbarer Nähe mit eigener SSID, jetzt läuft es seit drei Tagen stabil. ToiToiToi.

mit freundlichen Grüßen 

Till Preugschat

**Comment by mk-maddin** [comment]
Der Wattpilot ist leider sehr empfindlich was die WLAN verfügbarkeit angeht.
Mit dem iPhone hast du (für gewöhnlich) nur eine kurzzeitige Verbindung, während die Integration dauerhaft einen WebSocket offen hat.
Ich persönlich gehe davon aus, dass dies mit Abschaltung des HotSpot vom Wattpilot wahrscheinlich deutlich besser laufen würde - entsprechenden Feature Request zum Abschalten des HotSpot bei Fronius gibt es bereits, aber leider noch nicht implementiert.

Hast du mal probiert direkt über die API shell zuzugreifen? https://github.com/joscha82/wattpilot
Hast du hier equivalente Probleme?

**Comment by tpreugsc** [comment]
Ah, so fit bin ich nicht. Ich kann nur gut Dinge von anderen nutzen. 😂
Heute hat sich der Wattpilot doch wieder verabschiedet. Komplett aufgehängt, laden ging auch nicht. Jetzt teste ich mal, ob es am LED standby liegen könnte. Scheint mir nicht recht ausgereift, insbesondere das wlan-Verhalten ist wirklich katastrophal.
